"""
Nifty 500 (approx) NSE ticker list for use with yfinance (.NS suffix).
This is a static snapshot — index constituents change periodically.
Re-fetch an updated list from NSE's official site (niftyindices.com) every
few months and replace this file if you want to stay current.

Source pattern for fetching fresh list yourself (requires NSE access):
https://www.niftyindices.com/IndexConstituent/ind_nifty500list.csv
"""

HALAL_COMPLIENT_SYMBOLS_MORE_THAN_2000_CR = [   # Market capitilization more than 2000 Cr
    "3MINDIA","AAKASH","AANCHALISP","AARTIDRUGS","AARTIPHARM","ABFRL","ABHAPOWER","ABLBL","ABREL","ABRIL","ACC","ACCEL","ACE","ACI","ACUTAAS","ADDICTIVE","ADESHWAR","ADITYASP","ADL","ADOR","AEQUS","AEROFLEX","AETHER","AFCONS","AFLTD","AGARWALEYE","AGIIL","AGROPHOS","AHLADA","AIMCOPEST","AIMTRON","AJANTPHARM","AJMERA","AJOONI","AKI","AKSHAR","AKUMS","ALFATRAN","ALIVUS","ALKALI","ALKEM","ALKOSIGN","ALKYLAMINE","ALPEXSOLAR","AMBER","AMBEY","AMBOARGI","AMBUJACEM","AMCOIND","AMEYA","AMKAY","ANANTRAJ","ANGEL","ANJANI","ANSALAPI","ANSALBU","ANSALHSG","ANTELOPUS","ANTHEM","ANUP","APARINDS","APCOTEXIND","APLAPOLLO","APLLTD","APOLLO","APOLLOHOSP","APOLLOIN","APOLLOPIPE","APOLLOTYRE","ARABIAN","ARCIIL","AER&M","AREXMIS","ARISTO","ARITAS","ARKADE","ARMAN","ARMOUR","ARTEMISMED","ARUNAYA","ARVIND","ARVINDFASN","ARVINDPORT","ARVSMART","ARYAVAN","ASHALOG","ASHAPURMIN","ASHIANA","ASIANPAINT","ASKAUTOLTD","ASMTEC","ASSOCER","ASTERDM","ASTRAL","ATCENERGY","ATGL","ATHENAGLO","ATHERENERG","ATHPOLY","ATLANTAELE","ATUL","AUROPHARMA","AUTOAXLES","AVALON","AVANTEL","AVAX","AWL","AXISCADES",
    # B
    "BAJAJELEC","BALAMINES","BALKRISIND","BALMLAWRIE","BALUFORGE","BANARBEADS","BANCOINDIA","BANG","BANSALWIRE","BAPACK","BATAINDIA","BAYERCROP","BBOX","BECTORFOOD","BENCHMARK","BEPL","BERGEPAINT","BETA","BEWLTD","BGJL","BHAGCHEM","BJARATCOAL","BHARATRAS","BHARTIARTL","BHASKAGR","BIKAJJI","BIKEWO","BIOCON","BIOFILCHEM","BIOPOL","BIRDYS","BLISSGVS","BLUECHIPT","BLUEDART","BLUEJET","BLUESTARCO","BLUESTONE","BONLON","BOROLTD","BORORENEW","BOSCH-HCIL","BPCL","BRATANNIA","BUILDPRO","BULKCORP","BVCL",
    # C
    "CAMEXLTD","CAMPUS","CAPILLARY","CAPLIPOINT","CAPRICORN","CARBORUNIV","CARGOTRANS","CARRARO","CARYSIL","CCLINTER","CEATLTD","CELLO","CELLPOINT","CEMPRO","CENTURYPLY","CGPOWER","CGVAK","CHAMBLFERT","CHAMUND","CHANDNIMACH","CHEMPLASTS","CHENFERRO","CHENNPETRO","CHETANA","CHLOGIST","CHOKSI","CHORDIA","CHROME","CIANAGRO","CIEINDIA","CINEVISTA","CIPLA","CLARA","CLEAN","CLSL","CMSINFO","CNCRD","COALINDIA","COHANCE","COLINZ","CONCOR","CONCORDBIO","CONFIPET","CONSTRONIC","CONTPTR","COROMANDEL","CORONA","COUNCODOS","CPPLUS","CREATIVE","CROMPTON","CUMMINSIND","CURIS","CYIENT",
    # D
    "DAICHI","DAIKAFFI","DALBHARAT","DANGEE","DANISH","DANUBE","DARSHANORNA","DCAL","DDEVPLSTIK","DECCANTRAN","DECOMIC","DEEDEV","DEEM","DEEPAKCHEM","DEEPAKFERT","DEEPAKSP","DEEPINDS","DEFRAIL","DELHIVERY","DFPL","DHANLAXMI","DHANUKA","DIAMINESQ","DIAMONDYD","DIANATEA","DILIGENT","DIVISLAB","DIVYADHAN","DKEGL","DMART","DODLA","DOMS","DPABHUSHAN","DRAGARWQ","DRREDDY","DUROPACK","DUTRON","DYNAMIND",
    # E
    "EARTH","EFORCE","EIDPARRY","EIKO","ELECON","ELECTCAST","ELFORGE","ELGIEQUIP","EMAMILTD","EMCURE","EMIL","EMUDHRA","ENDURANCE","ENTERO","EPACK","EPACKPEB","EPIGRAL","EPL","ESABINDIA","ETHOSLTD","EUREKAFORB","EUROPRATIK","EVEREADY","EXCELLENT","EXICOM",
    # F
    "FAALCON","FACT","FIEMIND","FILATEX","FILTRA","FINELINE","FIRSTCRY","FLAIR","FLOMIC","FLUOROCHEM","FMGOETZE","FMNL","FONEBOX","FORCEMOT","FORTIS","FOSECOIND",
    # G
    "GABRIEL", "GAEL","GAIL","GALAGEX","GALAXYSURF","GALLANTT","GANECOS","GANESHHOU","GANGABATH","GANGAFORGE","GARGFUR","GARMNTMNTR","GATEWAY","GAYATRI","GENUSPOWER","GHCL","GIPCL","GKB","GLAND","GLENMARK","GML","GMMPFAUDLR","GODREJAGRO","GODREJCP","GOKEX","GOKULAGRO","GOLDIAM","GOPAL","GOTHIPL","GPARL","GPIL","GRANULES","GREAVESCOT","GREENPANEL","GREENPLY","GRINDWELL","GRWRHITECH","GSAUTO","GSPCROP","GSPL","GSS","GSTL","GTNINDS","GUFICBIO","GUJALKALI","GUJCONT","GUJCRAFT","GUJCRED","GUJGASLTD","GUJRAFFIA","GUJTERC","GUJTHEM","GULFOILLUB","GURUNANAK","GVT&D",
    # H
    "HAMPS","HAPPYFORGE","HARIKANTA","HARSHA","HATSUN","HAVELLS","HAWAENG","HAWKINCOOK","HCG","HEG","HEIDELBERG","HERITGFOOD","HFCL","HFIL","HIKAL","HINDALCO","HINDCOPPER","HINDUNILVR","HINDWAREAP","HIPOLIN","HLEGLAS","HMEML","HOLMARC","HPL","HSCL","HUBTOWN",
    # I
    "ICIL","ICLORGANIC","ICODEX","IDEALTECHO","IDENTIX","IEML","IFBIND","IGIL","IGL","IKS","IMFA","INANI","INCAP","INDCTST","INDIACEM","INDIGOPNTS","INDNIPPON","INDOTECH","INFONATIVE","INGERRAND","INNOVACAP","INOXINDIA","INOXWIND","INSECTICID","INTEGRITY","INTERARCH","INVICTA","IOLCP","IONEXCHANG","IPCALAB","IRONWOOD","ISGEC","ISMTLTD","ITI","IWEL","IYKOTHITE",
    # J
    "JAIBALAJI","JAMNAAUTO","JASH","JAYAGROGN","JBCHEPHARM","JETKNIT","JINDALSAW","JINDALSTEL","JISLJALEQS","KJCEMENT","JKIL","JKLAKSHMI","JKPAPER","JLHL","JPPOWER","JSL","JSWDULUX","JTEKTINDIA","JTLIND","JUBLCPL","JUBLINDS","JUNLPHARMA","JWL","JYOTICNC",
    # K
    "KAJARIACER","KALYANKJIL","KANSAINER","KAYNES","KDDL","KEEPLEARN","KEI","KENNAMET","KERNEX","KINGFA","KIRLFER","KIRLOSBROS","KIRLOSIND","KIRLPNU","KKCL","KLBRENG-B","KOLTEPATIL","KOVAI","KPEL","KPIGREEN","KPITTECH","KPL","KPRMILL","KRBL","KRN","KSB","KSCL","KSHITIJPOL","KSL",
    # L
    "LASA","LAURUSLABS","LENSKART","LGBBROSLTD","LINDEINDIA","LLOYDSENGG","LODHA","LOTUSDEV","LTFOODS","LUMAXIND","LUMAXTECH","LUPIN","LUXIND","LXCHEM",
    # M
    "MAHACORP","MAHLIFE","MAHLOG","MAKERSL","MANGCHEFER","MANGLMCEM","MANINDS","MANKIND","MARICO","MARINE","MARKSANS","MAXHEALTH","MEDANTA","MEDPLUS","METROBRAND","METROPOLIS","MGL","MIDHANI","MIDWESTLTD","MILTON","MINALIND","MINDACORP","MISHDESIGN","MMRUBBR-B","MODINSU","MOIL","MOLDTKPAC","MOREPENLAB","MOSCHIP","MOTHERSON","MPSLTD","MRF","MSPL","MSUMI","MTL",
    # N
    "NACDAC","NACLIND","NAMAN"
]

HALAL_COMPLIENT_SYMBOLS_LESS_THAN_2000_CR = [   # Market capitilization less than 2000 Cr
    "20MICRON","3CIT","AAREYDRUGS","AARNAV","AARTISURF","AASTHA","AAYUSHBULL","ABATEAS","ACCELYA","ACCENTMIC","ACCORDTS","ACESOFT","ACETEC","ACLD","ACLGATI","ACSTECH","ACTIVEINFR","ADHBHUTIN","ADHHATA","ADISOFT","ADJIA","ADMACH","ADON","ADORFO","ADVANCE","AEPL","AEROENTER","AERON","AERONEU","AESTHETIK","AFFORDABLE","AGARIND","AGARWALTUF","AGOL","AHCL","AICHAMP","AIKPIPES","AIRFLOA","AJANTSOY","AKANKSHA","AKSHARCHEM","ALEXANDER","ALICON","ALLCARGO","ALUFLUOR","ALUWIND","AMAL","AMARJOTHI","AMBALALSA","AMBANIORGO","AMBIKCO","AMINTAN","AMNPLST","ANDHRSUGAR","ANL","ANLON","ANNAPURNA","ANSINDUS","ANTGRAPHIC","ANUHPHR","APEX","APIS","APLAB","APMIN","APS","APSISAERO","ARCEEIN","ARCHITORG","ARCL","ARIES","ARROWHEAD","ARTNIRMAN","ARTSON","ARVEE","ASAHISONG","ASARFI","ASIAN","ASHIANTILES","ASPINWALL","ASPIRA","ASSOCIATED","ASTALLTD","ASTAR","ASTRONMULT","ATAREAL","ATAM","ATL","ATMASTCO","ATVPR","AUTOPINS","AVANA","AVEER","AVG","AVIANSH","AVTNPL","AWHCL","AYMSYNTEX","AZTEC",
    # B
    "BAFNAPH","BAJAJCARE","BAJAJST","BALAJIPHOS","BALAXI","BANGANGA","BANSTEA","BARODARY","BAROEXT","BASANTGL","BATLIBOI","BCCFUBA","BDI","BEARDSELL","BEEKAY","BEEZAASAN","BELLACASA","BEMHY","BERLDRG","BESTAGRO","BGWTATO","BHAGERIA","BHARATGEAR","BHARATROHAN","BHARATSE","BHARATWIRE","BHATIA","BHAVIK","BILLWIN","BIMETAL","BIRLACABLE","BIRLANU","BIRLAPREC","BIZOTIC","BKV","BLACKROSE","BLKASHYAP","BMW","BNALTD","BOROSCI","BOSS","BPAGRI","BPLPHARMA","BRADYM","BRANDMAN","BRAWN","BRGIL","BRIGHTBR","BRPL","BRRL","BUTTERFLY",
    # C
    "C2C","CANDOUR","CANTABIL","CAPPIPES","CENTENKA","CENTEXT","CEWWATER","CFF","CGRAPHICS","CHANDAN","CHEMCRUX","CHEMFAB","CHEMKART","CHOTHANI","CITYMAN","CITYSQUARE","CKKRETAIL","CLAYCRAFT","CLEDUCATE","CLN","CLSEL","CNL","COCHINM","CONCORD","CONTAINE","CONTI","CONTROLPR","CORDSCABLE","COSMICCRF","CPL","CPS","CRANEINFRA","CROWN","CTCL","CTLLAB","CUBEXTUB","CWD",
    # D
    "DANLAW","DAVIN","DBEIL","DCG","DCI","DCW","DEEP","DENISCHEM","DENTALKART","DESTINY","DEVINE","DEVLAB","DHABRIYA","DHAMPURE","DHANWEL", "DHARIWAL","DHARMAJ","DHILLON","DHTL","DICIND","DIFFNKG","DIRL","DLCL","DLTNCBL","DMCC","DOLFIN","DOLLAR","DPSCLTD","DRCSYSTEMS","SRONE","DSFCL","DTIL","DUROPLY","DYCL","DYNAMIC","DYNPRO",
    # E
    "EARKART","EASTBUILD","ECOBOAR","ECOLINE","ECOPLAST","ECORECO","EEPL","EIFFL","EKC","EKI","ELFIN","ELGNZ","ELIN","EMMFORCE","EMMIL","ENCOMPAS","ENVIRO","ESFL","ESPRIT","ETL","EUPHORIAIT","EUREKAI","EVERESTIND","EVERESTO","EXCELINDUS","EXXARO",
    # F
    "FABTECH","FAIRCHEMOR","FALCONTECH","FAMILYCARE","FAZE3Q","FERMENTA","FIL","FILATFASH","FLORACORP","FOCE","FOCUS","FORCAS","FORGEAUTO","FROG","FRONTSP","FTL","FWSTC",
    # G
    "GAJANAND","GALADA","GALAPREC","GALLARD","GALXBRG","GANDHAR","GANESHBE","GANESHCP","GANESHIN","GCONNECT","GEE","GENCON","GENESYS","GENXAI","GGAUTO","GGBL","GHCLTEXTIL","GILLANDERS","GINNIFILA","GIRIRAJ","GKP","GKSL","GLOBALVECT","GLOBOFFS","GLOSTERLTD","GMPL","GNA","GOCOLORS","GOELCONS","GOLDKART","GOLDSTAR","GOODRICKE","GOODYEAR","GPECO","GPTHEALTH","GPTINFRA","GRATEXI","GRCL","GREENCHEF","GRERENEW","GSLSU","GSMFOILS","GUJHYSPIN","GULFPETRO","GULPOLY",""
    # H
    "HAMPTON","HANMAN","HANNAH","HANSUGAR","HARDWYN","HARRMALAYA","HARSHDEEP","HEMANG","HEMORGANIC","HERANBA","HESTERBIO","HEUBACHIND","HEXAGON","HIGHENE","HIGREEN","HILINFRA","HILTON","HINDHARD","HINDTIN","HITECH","HITECHCORP","HITECHGEAR","HMAAGRA","HOACFOODS","HPAL","HPIL","HSIL","HUHTAMAKI","HVAX",
    # I
    "ICELECTRIC","ICEMAKE","ICL","IFGLEXPOR","IGARASHI","IGCL","IGLFXPL-B","IGPL","IKIO","IKOMA","INCREDIBLE","INDGELA","INDOKEM","INDONG","INDOUS","INDOWIND","INDSUCR","INDTERRAIN","INFINITY","INFINIUM","INFLAME","INFLUX","INM","INNOMET","INNOVATORS","INTEGRAEN","INTLCOMBQ","INVPRECQ","IPHL","IPL","IPRINGLTD","IRISDOREME","IRMENERGY","ISFT","ITALIANE","ITL","IVP","IWP","IZMO",
    # J
    "JAGANLAM","JAINIK","JAINMARMA","JAIPURKURT","JAKHARIA","JASCH","JAYBARMARU","JAYBEE","JAYSHREETEA","JAYSYN","JAYUSH","JCTLTD","JDORGOCHEM","JEYYAM","JFL","JFLLIFE","JGCHEM","JIGAR","JINDRILL","JIVIAL","JIWANRAM","JOCIL","JOINTECAED","JOSTS","JSTL",
    # K
    "KABRAEXTRU","KABSON","KACHCHH","KAIRA","KAJARIR","KALAMANDIR","KALANA","KALYANIFRG","KAMADGIRI","KAMOPAINTS","KANCHI","KANPRPLA","KANSHST","KASTURI","KATARIA","KATRSPG","KAYCEEI","KAYPOWR","KAYTEX","KDL","KECL","KELENRG","KEMISTAR","KEN","KENRIK","KESARENT","KESATPE","KESORAMIND","KGPETRO","KGVL","KHADIM","KHAITANLTD","KHAZANCHI","KIAASA","KILITCH","KISAN","KIZI","KKVAPOW","KLL","KMCSHIL","KMSMEDI","KNACK","KNAGRI","KOKUYOCMLN","KONTOR","KOPRAN","KOTHARIPET","KOTIK","KOTYARK","KPGEL","KPT","KRATECH","KRISHCA","KRISHIVAL","KRISHNA","KRITI","KRITIKA","KRITINUT","KROSS","KRSNAA","KUANTUM","KVFORGE","KVSCASTING","KVTOYS",
    # L
    "LABELKRAFT","LAKSHYA","LAMBODHARA","LANCER","LANDMARK","LATIMMETAL","LATTEYS","LAXMIPATI","LEHAR","LIBERTSHOE","LIKHITHA","LINC","LINKPH","LIOTECH","LOKESHMACH","LOTUSEYE","LOYAL","LRRPL","LTELEVATOR","LUXURY","LWSKNIT","LXMIATO","LYKALABS",
    # M
    "MAANALU","MACIND","MACOBSTECH","MACPOWER","MADHAVIPL","MAFIA","MAGENTA","MAGNAELQ","MAHALIFE","MAHASTEEL","MAHICKRA","MAINFRA","MAITREYA","MALLCOM","MALPANI","MAMATA","MANAKCOAT","MANAKIPETC","MANDEEP","MANGALAM","MANUGRAPH","MARCLOIRE","MARSHALL","MASON","MASTER","MAXIMUS","MAXVOLT","MAYASHEEL","MAYUR","MBEL","MCON","MCPL","MDL","MEAPL","MEDICAMEO","MEDICO","MEDIORG","MEERA","MEGATHERM","MEHAI","MENNPIS","MENONBE","MERCURYEV","MERCURYLAB","MESON","METAINFO","METALCO","MFML","MHHL","MHLXMIU","MHSGRMS","MICEL","MIDINDIA","MILESTONE","MILLENNIUM","MIRZAINT","MISQUITA","MITTAL","MKEXIM","MKPL","MLKFOOD","MMP","MNFL","MBILISE","MODAIRY","MODIS","MODTHREAD","MODULEX","MOKSH","MOL","MOLDTECH","MONOLITH","MONTECARLO","MORGANITE","MOTISONS","MOXSH","MPKSTEELS","MRP","MRTX","MSECL","MUFTI","MUNJALAU","MURUDCERA","MWL",
    # N
    ""
]

NIFTY_500_SYMBOLS = [
    "ACUTAAS","RELIANCE","TCS","HDFCBANK","ICICIBANK","INFY","BHARTIARTL","SBIN","LICI",
    "ITC","HINDUNILVR","LT","BAJFINANCE","HCLTECH","MARUTI","SUNPHARMA","KOTAKBANK",
    "AXISBANK","ADANIENT","TITAN","ASIANPAINT","ULTRACEMCO","ADANIPORTS","NTPC","BAJAJFINSV",
    "ONGC","NESTLEIND","WIPRO","M&M","JSWSTEEL","POWERGRID","COALINDIA","TATAMOTORS",
    "BAJAJ-AUTO","TATASTEEL","GRASIM","HDFCLIFE","SBILIFE","TECHM","ADANIGREEN","INDUSINDBK",
    "CIPLA","DRREDDY","EICHERMOT","APOLLOHOSP","DIVISLAB","BRITANNIA","HEROMOTOCO","BPCL",
    "VEDL","TATACONSUM","SHREECEM","UPL","HINDALCO","GODREJCP","DABUR","PIDILITIND",
    "MARICO","COLPAL","AMBUJACEM","ACC","JINDALSTEL","SAIL","NMDC","HINDZINC",
    "PNB","BANKBARODA","CANBK","UNIONBANK","IDFCFIRSTB","FEDERALBNK","AUBANK","BANDHANBNK",
    "RBLBANK","YESBANK","IDBI","INDIANB","BANKINDIA","CENTRALBK","UCOBANK","PSB",
    "LTIM","MPHASIS","COFORGE","PERSISTENT","LTTS","OFSS","TATAELXSI","KPITTECH",
    "ZOMATO","NYKAA","PAYTM","POLICYBZR","DELHIVERY","IRCTC","INDIGO","NAUKRI",
    "DMART","TRENT","ABFRL","VBL","UBL","RADICO","MCDOWELL-N","GODFRYPHLP",
    "PGHH","GILLETTE","HONAUT","ABBOTINDIA","PFIZER","GLAXO","SANOFI","ALKEM",
    "TORNTPHARM","LUPIN","AUROPHARMA","CADILAHC","BIOCON","GLENMARK","IPCALAB","LALPATHLAB",
    "METROPOLIS","FORTIS","MAXHEALTH","NH","SYNGENE","GRANULES","NATCOPHARM","AJANTPHARM",
    "GMRINFRA","GVK","IRB","NHPC","SJVN","TATAPOWER","ADANIPOWER","TORNTPOWER",
    "CESC","NLCINDIA","RECLTD","PFC","IRFC","HUDCO","IREDA","PNBHOUSING",
    "LICHSGFIN","CANFINHOME","REPCO","GICRE","NIACL","ICICIGI","ICICIPRULI","HDFCAMC",
    "NAM-INDIA","UTIAMC","ABSLAMC","MOTILALOFS","IIFL","CDSL","BSE","MCX",
    "ANGELONE","CAMS","KFINTECH","CRISIL","CARERATING","ICRA","SUNDARMFIN","CHOLAFIN",
    "MUTHOOTFIN","MANAPPURAM","BAJAJHLDNG","SHRIRAMFIN","M&MFIN","LTF","PEL","SRTRANSFIN",
    "ASHOKLEY","TVSMOTOR","BALKRISIND","MRF","APOLLOTYRE","CEAT","JKTYRE","EXIDEIND",
    "AMARAJABAT","BOSCHLTD","MOTHERSON","BHARATFORG","ENDURANCE","SUNDRMFAST","SCHAEFFLER","TIINDIA",
    "CUMMINSIND","SIEMENS","ABB","HONDAPOWER","THERMAX","BHEL","BEL","HAL",
    "BEML","GRSE","COCHINSHIP","MAZDOCK","DATAPATTNS","ASTRAMICRO","PARAS","MTARTECH",
    "ZENTEC","KAYNES","DIXON","AMBER","VOLTAS","BLUESTARCO","WHIRLPOOL","CROMPTON",
    "HAVELLS","POLYCAB","KEI","FINOLEX","VGUARD","ORIENTELEC","SYMPHONY","RAJESHEXPO",
    "TITANBIO","KALYANKJIL","SENCO","THANGAMAYL","PCJEWELLER","RAJESH","VAIBHAVGBL","ADITYAB",
    "PAGEIND","ARVIND","RAYMOND","WELSPUNIND","KPRMILL","TRIDENT","VARDHMAN","SIYARAM",
    "GOKEX","INDOCOUNT","HIMATSEIDE","NITINSPIN","SPENTEX","RUPA","LUXIND","DOLLAR",
    "JUBLFOOD","WESTLIFE","DEVYANI","SAPPHIRE","BARBEQUE","SPECIALITY","EASEMYTRIP","THOMASCOOK",
    "MAHINDCIE","MAHLOG","TCI","VRL","GATI","ALLCARGO","TCIEXP","SNOWMAN",
    "CONCOR","GUJPIPAVAV","ADANIPORTS","JSWINFRA","ESSARSHPNG","SCI","GESHIP","VARUNBEV",
    "UNITDSPR","TATACOFFEE","CCL","EIDPARRY","BALRAMCHIN","DALMIASUG","DHAMPURSUG","TRIVENI",
    "BAJAJHIND","RENUKA","KAVERI","RALLIS","UPL","COROMANDEL","CHAMBLFERT","GNFC",
    "GSFC","DEEPAKNTR","AARTIIND","ATUL","VINATIORGA","NAVINFLUOR","FLUOROCHEM","SRF",
    "PIIND","CLEAN","FINEORG","NOCIL","TATACHEM","GHCL","DCMSHRIRAM","PHILLIPCARB",
    "JUBLINGREA","SOLARINDS","IDEA","TATACOMM","GTPL","HFCL","STERLITETECH","RAILTEL",
    "TEJASNET","ROUTE","TANLA","SUBEXLTD","ONMOBILE","NUCLEUS","INTELLECT","RAMCOSYS",
    "SONATSOFTW","ZENSAR","HEXAWARE","BIRLASOFT","NEWGEN","HAPPSTMNDS","MASTEK","CYIENT",
    "RATEGAIN","LATENTVIEW","MAPMYINDIA","TATATECH","KPIGREEN","WAAREE","INOXWIND","SUZLON",
    "ORIENTGREEN","BOROSIL","BORORENEW","WEBSOL","INSOLATION","GENSOL","ACMESOLAR","SWSOLAR",
    "JPPOWER","RPOWER","RELINFRA","RELCAPITAL","JSWENERGY","TORNTPOWER","KEC","SADBHAV",
    "PNCINFRA","KNRCON","HGINFRA","ASHOKA","NCC","JKIL","WELCORP","RHIM",
    "ORIENTCEM","JKCEMENT","RAMCOCEM","HEIDELBERG","BIRLACORPN","STARCEMENT","INDIACEM","DECCAN",
    "PRISMCEM","SAGCEM","KESORAMIND","KAJARIACER","SOMANYCERA","CERA","HSIL","ASTRAL",
    "SUPREMEIND","FINPIPE","PRINCEPIPE","APLLTD","JISLJALEQS","EVERESTIND","VISAKAIND","RAMCO",
    "GREENPLY","CENTURYPLY","ARCHIDPLY","UTTAMSUGAR","STYLAMIND","GREENPANEL","ACTIONCONS","SHYAMMETL",
]

def get_tickers(suffix=".NS"):
    """Return Nifty 500 tickers with NSE suffix for yfinance, deduplicated."""
    seen = set()
    out = []
    # for s in NIFTY_500_SYMBOLS:
    for s in HALAL_COMPLIENT_SYMBOLS_MORE_THAN_2000_CR + NIFTY_500_SYMBOLS:
        if s not in seen:
            seen.add(s)
            out.append(s + suffix)
    return out
